services:
  - type: web
    name: Textbook-Physical-Ai-and-Humanoid-Robotics-Course
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
